from typing import Protocol

from ..models import CacheEntry


class CacheStore(Protocol):
  def get_exact(self, scope, fingerprint) -> CacheEntry | None: ...
  def search(self, scope, embedding, limit) -> list[tuple[CacheEntry, float]]: ...
  def put(self, entry, embedding) -> None: ...
  def touch(self, scope, fingerprint) -> None: ...  # your increment_count
  def evict_expired(self) -> int: ...
  def clear(self, scope=None) -> int: ...
