from typing import Protocol

from ..models import CacheEntry, Embedding


class CacheStore(Protocol):
  def get_exact(self, scope: str, fingerprint: str) -> CacheEntry | None: ...
  def search(
    self, scope: str, embedding: Embedding, limit: int
  ) -> list[tuple[CacheEntry, float]]: ...
  def put(self, entry: CacheEntry, embedding: Embedding) -> None: ...
  def touch(self, scope: str, fingerprint: str) -> None: ...
  def evict_expired(self) -> int: ...
  def purge(self) -> int: ...
  def clear(self, scope: str) -> int: ...
